name: Update data

on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "github"
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: report
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn clean install exec:java -Pgithub
          if ( ! git diff --exit-code &>/dev/null ); then 
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git commit -a -m "Updated data"
            git push
          fi
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build dashboard
        run: mvn clean install exec:java -Pdashboard -Dpublish
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
